<script>
	import Card from '$lib/Card.svelte';
    
</script>

<svelte:head>
    <title>Art and Coding | Denis Protopopov</title> 
	<meta property="og:title" content="Denis Protopopov"/>
	<meta property="og:description" content="Artist and researcher that works at the intersection of technologies, media, visual and performative arts."/>

	<meta name="twitter:title" content="Denis Protopopov"/>
	<meta name="twitter:description" content="Artist and researcher that works at the intersection of technologies, media, visual and performative arts."/>

</svelte:head>

<main class="container">
	<Card class="blue card">
		<a href="/art/cv">
		<p class="header-in-box">Captical Voyage</p>
		<p class="text-in-box">
			Augmented reality performance that investigates the balance of power between body and code. Native iOS app build with ARKit.
		</p>
		</a>
	</Card>

	<!-- svelte-ignore a11y-missing-content -->
	<Card class="cv card"><a href="/art/cv"></a></Card>

	<Card class="dark card">
		<a href="/art/labor">
		<p class="header-in-box">Labor in Question</p>
		<p class="text-in-box">
			An exploratory three.js video game addressing the identity of an industrial worker in post-soviet Karelia.
		</p>
		</a>
	</Card>

	<!-- svelte-ignore a11y-missing-content -->
	<Card class="labor card"><a href="/art/labor"></a></Card>

	<Card class="grey card">
		<a href="/art/rockets">
		<p class="header-in-box">Rockets Take Off and Crash and Scatter in the Air</p>
		<p class="text-in-box">
			Performance about the connections between everything, which is generated by the algorithm before each show.
		</p>
	</a>
	</Card>

	<!-- svelte-ignore a11y-missing-content -->
	<Card class="rockets card"><a href="/art/rockets"></a></Card>

	<Card class="beige card">
		<a href="/art/ie">
		<p class="header-in-box">Inner Emigration</p>
		<p class="text-in-box">
			Multimedia performance about queer bodies and sensuality in an algorithmic space.
		</p>
	</a>
	</Card>

	<Card class="ie card"><a href="/art/ie"></a></Card>

	<Card class="brown card">
		<a href="/art/deepstopwords">
		<p class="header-in-box">Deep Stop Words</p>
		<p class="text-in-box">
			The work investigates books, texts and graphic visualizations as tools for proving and constructing rational knowledge.
		</p>
	</a>
	</Card>

	<Card class="deep card"><a href="/art/deepstopwords"></a></Card>

	<Card class="green card">
		<a href="/art/damnthecomplexity">
		<p class="header-in-box">Damn the Complexity</p>
		<p class="text-in-box">
			Audiovisual project that draws connections between technologies and spirituality.
		</p>
	</a>
	</Card>

	<Card class="damn card"><a href="/art/damnthecomplexity"></a></Card>
</main>

<style>
  p {
    font-family: 'Cooshing-Book', regular;
    color: rgb(255, 255, 255);
		margin: 0;
		padding: 10% 10% 10%;
		position: absolute;
		left: 0;
		right: 0;
  }
	.container {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		justify-content: center;
	}
	.header-in-box {
		font-size: clamp(17px, 4vh, 30px);
	}

	.text-in-box {
		font-size: clamp(12px, 3vh, 18px);
		bottom: 0;
	}
	.container :global(.blue) {
		background-color: rgb(52, 72, 252);
	}
  .container :global(.green) {
		background-color: rgb(40, 120, 2);
	}
  .container :global(.brown) {
		background-color: rgb(173, 83, 47);
	}
  .container :global(.beige) {
		background-color: rgb(228, 179, 141);
	}
	.container :global(.grey) {
		background-color: rgb(94, 97, 122);
	}
	.container :global(.dark) {
		background-color: rgb(55, 56, 61);
	}
	.container :global(.cv) {
		background-image: url("/images/cv0.png");
	}
	

	.container :global(.rockets) {
		background-image: url("/images/rockets0.jpg");
	}

	.container :global(.mm) {
		background-image: url("/images/mm0.jpeg");
	}

	.container :global(.ie) {
		background-image: url("/images/ie.png");
	}

	.container :global(.deep) {
		background-image: url("/images/deep0.jpg");
	}

	.container :global(.damn) {
		background-image: url("/images/damn.jpeg");
	}
	.container :global(.labor) {
		background-image: url("/images/factory.png");
	}
	

	a {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}
</style>
